spring:
  ai:
    mcp:
      server:
        type: async
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true

logging:
  level:
    root: info
    org:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'
